/**
 * Word Frequency Lists for RSVP Complexity Scoring
 * 
 * These lists are used to estimate word complexity based on frequency.
 * Common words are recognized faster and need less display time.
 * 
 * Sources: Derived from common word frequency lists (Corpus of Contemporary American English)
 */

/**
 * Top 1000 most common English words
 * These are instantly recognized and can be displayed faster
 */
export const COMMON_WORDS_1K = new Set([
  // Articles, pronouns, prepositions, conjunctions
  'a', 'an', 'the', 'and', 'or', 'but', 'if', 'then', 'else', 'when',
  'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during',
  'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out',
  'on', 'off', 'over', 'under', 'again', 'further', 'once', 'here', 'there', 'where',
  'why', 'how', 'all', 'each', 'few', 'more', 'most', 'other', 'some', 'such',
  'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very',
  'just', 'also', 'now', 'well', 'even', 'back', 'any', 'both', 'much', 'many',
  
  // Pronouns
  'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your',
  'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers',
  'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what',
  'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are',
  'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do',
  'does', 'did', 'doing', 'would', 'should', 'could', 'ought', 'might', 'must', 'shall',
  'will', 'can', 'may', 'need', 'dare', 'used',
  
  // Common verbs
  'say', 'said', 'get', 'got', 'go', 'went', 'gone', 'going', 'make', 'made',
  'know', 'knew', 'known', 'think', 'thought', 'take', 'took', 'taken', 'see', 'saw',
  'seen', 'come', 'came', 'want', 'use', 'used', 'find', 'found', 'give', 'gave',
  'given', 'tell', 'told', 'work', 'worked', 'call', 'called', 'try', 'tried', 'ask',
  'asked', 'put', 'seem', 'seemed', 'leave', 'left', 'keep', 'kept', 'let', 'begin',
  'began', 'begun', 'show', 'showed', 'shown', 'hear', 'heard', 'play', 'played', 'run',
  'ran', 'move', 'moved', 'live', 'lived', 'believe', 'believed', 'hold', 'held', 'bring',
  'brought', 'happen', 'happened', 'write', 'wrote', 'written', 'provide', 'provided', 'sit', 'sat',
  'stand', 'stood', 'lose', 'lost', 'pay', 'paid', 'meet', 'met', 'include', 'included',
  'continue', 'continued', 'set', 'learn', 'learned', 'change', 'changed', 'lead', 'led', 'understand',
  'understood', 'watch', 'watched', 'follow', 'followed', 'stop', 'stopped', 'create', 'created', 'speak',
  'spoke', 'spoken', 'read', 'allow', 'allowed', 'add', 'added', 'spend', 'spent', 'grow',
  'grew', 'grown', 'open', 'opened', 'walk', 'walked', 'win', 'won', 'offer', 'offered',
  'remember', 'remembered', 'love', 'loved', 'consider', 'considered', 'appear', 'appeared', 'buy', 'bought',
  'wait', 'waited', 'serve', 'served', 'die', 'died', 'send', 'sent', 'expect', 'expected',
  'build', 'built', 'stay', 'stayed', 'fall', 'fell', 'fallen', 'cut', 'reach', 'reached',
  'kill', 'killed', 'remain', 'remained', 'suggest', 'suggested', 'raise', 'raised', 'pass', 'passed',
  'sell', 'sold', 'require', 'required', 'report', 'reported', 'decide', 'decided', 'pull', 'pulled',
  
  // Common nouns
  'time', 'year', 'people', 'way', 'day', 'man', 'woman', 'child', 'world', 'life',
  'hand', 'part', 'place', 'case', 'week', 'company', 'system', 'program', 'question', 'work',
  'government', 'number', 'night', 'point', 'home', 'water', 'room', 'mother', 'area', 'money',
  'story', 'fact', 'month', 'lot', 'right', 'study', 'book', 'eye', 'job', 'word',
  'business', 'issue', 'side', 'kind', 'head', 'house', 'service', 'friend', 'father', 'power',
  'hour', 'game', 'line', 'end', 'member', 'law', 'car', 'city', 'community', 'name',
  'president', 'team', 'minute', 'idea', 'kid', 'body', 'information', 'nothing', 'ago', 'right',
  'lead', 'social', 'long', 'little', 'thing', 'own', 'state', 'level', 'office', 'door',
  'health', 'person', 'art', 'war', 'history', 'party', 'result', 'change', 'morning', 'reason',
  'research', 'girl', 'guy', 'moment', 'air', 'teacher', 'force', 'education',
  
  // Common adjectives
  'good', 'new', 'first', 'last', 'long', 'great', 'little', 'own', 'other', 'old',
  'right', 'big', 'high', 'different', 'small', 'large', 'next', 'early', 'young', 'important',
  'few', 'public', 'bad', 'same', 'able', 'human', 'local', 'sure', 'free', 'better',
  'best', 'true', 'whole', 'real', 'full', 'hard', 'possible', 'special', 'open', 'clear',
  'recent', 'certain', 'personal', 'white', 'black', 'american', 'low', 'national', 'political', 'social',
  'major', 'economic', 'strong', 'available', 'single', 'common', 'international', 'likely', 'simple', 'hot',
  'dead', 'poor', 'nice', 'late', 'easy', 'necessary', 'federal', 'financial', 'private', 'foreign',
  'serious', 'light', 'general', 'various', 'physical', 'natural', 'final', 'main', 'former', 'legal',
  'similar', 'medical', 'current', 'dark', 'wrong', 'total', 'short', 'left', 'past', 'close',
  
  // Common adverbs
  'really', 'always', 'never', 'often', 'sometimes', 'usually', 'still', 'already', 'almost', 'probably',
  'actually', 'perhaps', 'maybe', 'certainly', 'quickly', 'slowly', 'finally', 'recently', 'especially', 'exactly',
  'simply', 'nearly', 'clearly', 'enough', 'away', 'together', 'likely', 'today', 'ever', 'yet',
]);

/**
 * Top 5000 most common English words
 * These are recognized easily and need standard display time
 */
export const COMMON_WORDS_5K = new Set([
  ...COMMON_WORDS_1K,
  
  // Extended verbs
  'accept', 'achieve', 'act', 'admit', 'affect', 'afford', 'agree', 'aim', 'announce', 'answer',
  'apply', 'argue', 'arrange', 'arrive', 'assume', 'attack', 'attempt', 'attend', 'attract', 'avoid',
  'base', 'beat', 'become', 'belong', 'blame', 'block', 'blow', 'bother', 'break', 'breathe',
  'burn', 'carry', 'catch', 'cause', 'celebrate', 'challenge', 'charge', 'check', 'choose', 'claim',
  'clean', 'climb', 'close', 'collect', 'combine', 'commit', 'compare', 'complain', 'complete', 'concentrate',
  'concern', 'confirm', 'connect', 'consist', 'contact', 'contain', 'contribute', 'control', 'cook', 'copy',
  'correct', 'cost', 'count', 'cover', 'cross', 'cry', 'damage', 'dance', 'deal', 'deliver',
  'demand', 'deny', 'depend', 'describe', 'design', 'destroy', 'determine', 'develop', 'disappear', 'discover',
  'discuss', 'divide', 'doubt', 'draw', 'dress', 'drink', 'drive', 'drop', 'eat', 'emerge',
  'enable', 'encourage', 'enjoy', 'ensure', 'enter', 'escape', 'establish', 'examine', 'exist', 'expand',
  'experience', 'explain', 'explore', 'express', 'extend', 'face', 'fail', 'fear', 'feed', 'feel',
  'fight', 'fill', 'finish', 'fit', 'fix', 'fly', 'focus', 'force', 'forget', 'form',
  'gain', 'gather', 'generate', 'grab', 'grant', 'guess', 'handle', 'hang', 'hate', 'head',
  'help', 'hide', 'hit', 'hope', 'hurt', 'identify', 'ignore', 'imagine', 'imply', 'impose',
  'improve', 'increase', 'indicate', 'influence', 'inform', 'insist', 'install', 'intend', 'introduce', 'invest',
  'investigate', 'invite', 'involve', 'join', 'judge', 'jump', 'justify', 'kick', 'knock', 'lack',
  'last', 'laugh', 'launch', 'lay', 'lie', 'lift', 'like', 'limit', 'link', 'listen',
  'load', 'locate', 'lock', 'look', 'maintain', 'manage', 'mark', 'marry', 'match', 'matter',
  'mean', 'measure', 'mention', 'mind', 'miss', 'mix', 'monitor', 'name', 'negotiate', 'note',
  'notice', 'obtain', 'occupy', 'occur', 'operate', 'order', 'organize', 'overcome', 'own', 'participate',
  'perform', 'permit', 'persuade', 'pick', 'place', 'plan', 'point', 'position', 'possess', 'post',
  'pour', 'practice', 'prefer', 'prepare', 'present', 'preserve', 'press', 'prevent', 'print', 'process',
  'produce', 'promise', 'promote', 'propose', 'protect', 'prove', 'publish', 'purchase', 'pursue', 'push',
  'race', 'realize', 'receive', 'recognize', 'recommend', 'record', 'recover', 'reduce', 'refer', 'reflect',
  'refuse', 'regard', 'register', 'reject', 'relate', 'release', 'rely', 'remove', 'repeat', 'replace',
  'represent', 'request', 'resolve', 'respond', 'rest', 'restore', 'restrict', 'retain', 'retire', 'return',
  'reveal', 'review', 'ride', 'ring', 'rise', 'risk', 'roll', 'rule', 'rush', 'satisfy',
  'save', 'search', 'secure', 'seek', 'select', 'separate', 'settle', 'shake', 'shape', 'share',
  'shift', 'shoot', 'shop', 'shout', 'shut', 'sign', 'sing', 'sleep', 'slip', 'smile',
  'smoke', 'solve', 'sort', 'sound', 'split', 'spread', 'steal', 'stick', 'store', 'strike',
  'struggle', 'study', 'submit', 'succeed', 'suffer', 'suit', 'supply', 'support', 'suppose', 'surprise',
  'surround', 'survive', 'suspect', 'swim', 'switch', 'talk', 'target', 'taste', 'teach', 'tear',
  'tend', 'test', 'thank', 'throw', 'tie', 'touch', 'track', 'trade', 'train', 'transfer',
  'transform', 'translate', 'travel', 'treat', 'trigger', 'trust', 'turn', 'undergo', 'undertake', 'upset',
  'urge', 'vary', 'visit', 'vote', 'wake', 'warn', 'wash', 'waste', 'wear', 'welcome',
  'wish', 'withdraw', 'wonder', 'worry', 'wrap', 'yield',
  
  // Extended nouns
  'ability', 'absence', 'abuse', 'access', 'accident', 'account', 'achievement', 'action', 'activity', 'actor',
  'address', 'administration', 'adult', 'advantage', 'advice', 'affair', 'afternoon', 'age', 'agency', 'agent',
  'agreement', 'agriculture', 'aircraft', 'airport', 'alarm', 'album', 'alcohol', 'alternative', 'ambition', 'analysis',
  'analyst', 'anger', 'angle', 'animal', 'announcement', 'anxiety', 'apartment', 'appeal', 'appearance', 'application',
  'approach', 'argument', 'arm', 'army', 'arrangement', 'arrest', 'arrival', 'article', 'artist', 'aspect',
  'assembly', 'assessment', 'asset', 'assignment', 'assistance', 'assistant', 'association', 'assumption', 'atmosphere', 'attack',
  'attempt', 'attention', 'attitude', 'audience', 'author', 'authority', 'average', 'award', 'awareness', 'background',
  'balance', 'ball', 'band', 'bank', 'bar', 'base', 'baseball', 'basic', 'basis', 'basket',
  'basketball', 'bath', 'bathroom', 'battery', 'battle', 'beach', 'bear', 'beauty', 'bed', 'bedroom',
  'beer', 'beginning', 'behavior', 'belief', 'bell', 'benefit', 'bike', 'bill', 'bird', 'birth',
  'bit', 'block', 'blood', 'blue', 'board', 'boat', 'bomb', 'bond', 'bone', 'bonus',
  'border', 'boss', 'bottle', 'bottom', 'boundary', 'bowl', 'box', 'boy', 'brain', 'branch',
  'brand', 'bread', 'breakfast', 'breast', 'breath', 'brick', 'bridge', 'brief', 'brother', 'brown',
  'brush', 'budget', 'building', 'bullet', 'burden', 'bus', 'button', 'buyer', 'cabinet', 'cable',
  'cake', 'camera', 'camp', 'campaign', 'campus', 'cancer', 'candidate', 'cap', 'capital', 'captain',
  'card', 'care', 'career', 'carpet', 'carrier', 'cash', 'cat', 'category', 'cause', 'ceiling',
  'cell', 'center', 'central', 'century', 'ceremony', 'chain', 'chair', 'chairman', 'challenge', 'chamber',
  'champion', 'championship', 'chance', 'channel', 'chapter', 'character', 'characteristic', 'chart', 'cheese', 'chemical',
  'chest', 'chicken', 'chief', 'childhood', 'chip', 'chocolate', 'choice', 'church', 'cigarette', 'circle',
  'circumstance', 'citizen', 'class', 'classic', 'classroom', 'client', 'climate', 'clock', 'clothes', 'clothing',
  'cloud', 'club', 'coach', 'coal', 'coast', 'coat', 'code', 'coffee', 'cold', 'collapse',
  'colleague', 'collection', 'college', 'color', 'column', 'combination', 'comedy', 'comfort', 'command', 'comment',
  'commission', 'commitment', 'committee', 'communication', 'comparison', 'competition', 'competitor', 'complaint', 'complex', 'component',
  'computer', 'concentration', 'concept', 'concern', 'conclusion', 'condition', 'conference', 'confidence', 'conflict', 'confusion',
  'congress', 'connection', 'consciousness', 'consequence', 'consideration', 'construction', 'consultant', 'consumer', 'contact', 'content',
  'contest', 'context', 'contract', 'contrast', 'contribution', 'conversation', 'conviction', 'cookie', 'cooking', 'cooperation',
  'cop', 'corner', 'corporation', 'cost', 'cotton', 'couch', 'council', 'count', 'counter', 'country',
  'county', 'couple', 'courage', 'course', 'court', 'cousin', 'coverage', 'cow', 'crack', 'craft',
  'crash', 'crazy', 'cream', 'creation', 'creature', 'credit', 'crew', 'crime', 'criminal', 'crisis',
  'criticism', 'crop', 'cross', 'crowd', 'culture', 'cup', 'currency', 'current', 'curriculum', 'customer',
  'cycle', 'dad', 'dairy', 'damage', 'dance', 'danger', 'dark', 'darkness', 'data', 'database',
  'date', 'daughter', 'deal', 'dealer', 'death', 'debate', 'debt', 'decade', 'decision', 'deck',
  'declaration', 'decline', 'deep', 'deer', 'defeat', 'defense', 'deficit', 'definition', 'degree', 'delay',
  'delivery', 'demand', 'democracy', 'demonstration', 'department', 'deposit', 'depression', 'depth', 'description', 'desert',
  'desk', 'destination', 'detail', 'determination', 'device', 'dialogue', 'diet', 'difference', 'difficulty', 'dimension',
  'dinner', 'direction', 'director', 'dirt', 'disability', 'disaster', 'discipline', 'discount', 'discovery', 'discrimination',
  'discussion', 'disease', 'dish', 'disk', 'display', 'dispute', 'distance', 'distinction', 'distribution', 'district',
  'diversity', 'division', 'doctor', 'document', 'dog', 'dollar', 'domain', 'door', 'double', 'downtown',
  'dozen', 'draft', 'drama', 'dream', 'dress', 'drink', 'driver', 'drug', 'dust', 'duty',
  'ear', 'earth', 'ease', 'east', 'economy', 'edge', 'edition', 'editor', 'effect', 'effectiveness',
  'efficiency', 'effort', 'egg', 'election', 'element', 'emergency', 'emotion', 'emphasis', 'empire', 'employee',
  'employer', 'employment', 'end', 'enemy', 'energy', 'enforcement', 'engagement', 'engine', 'engineer', 'engineering',
  'entertainment', 'enthusiasm', 'entrance', 'entry', 'environment', 'episode', 'equal', 'equipment', 'era', 'error',
  'escape', 'essay', 'estate', 'estimate', 'ethics', 'evaluation', 'evening', 'event', 'evidence', 'evolution',
  'examination', 'example', 'exception', 'exchange', 'excitement', 'excuse', 'executive', 'exercise', 'exhibition', 'existence',
  'expansion', 'expectation', 'expense', 'experience', 'experiment', 'expert', 'explanation', 'explosion', 'export', 'exposure',
  'extension', 'extent', 'extreme', 'fabric', 'facility', 'factory', 'faculty', 'failure', 'faith', 'fall',
  'fame', 'familiar', 'family', 'fan', 'farm', 'farmer', 'fashion', 'fat', 'fate', 'fault',
  'favor', 'favorite', 'feature', 'fee', 'feedback', 'feeling', 'fellow', 'female', 'fence', 'festival',
  'fiber', 'fiction', 'field', 'fifth', 'figure', 'file', 'film', 'final', 'finding', 'finger',
  'fire', 'firm', 'fish', 'fishing', 'fitness', 'flag', 'flame', 'flash', 'flat', 'flavor',
  'flesh', 'flexibility', 'flight', 'floor', 'flow', 'flower', 'fly', 'folder', 'folk', 'food',
  'foot', 'football', 'forest', 'form', 'formal', 'format', 'formation', 'formula', 'fortune', 'forum',
  'forward', 'foundation', 'founder', 'frame', 'framework', 'freedom', 'frequency', 'fruit', 'frustration', 'fuel',
  'function', 'fund', 'funeral', 'furniture', 'future', 'gain', 'gallery', 'gap', 'garage', 'garden',
  'gas', 'gate', 'gear', 'gender', 'gene', 'generation', 'genre', 'gentleman', 'gift', 'glass',
  'glove', 'goal', 'god', 'gold', 'golf', 'grade', 'grain', 'grand', 'grandfather', 'grandmother',
  'grant', 'grass', 'grave', 'green', 'grocery', 'ground', 'group', 'growth', 'guarantee', 'guard',
  'guest', 'guide', 'guideline', 'guilt', 'guitar', 'gun', 'habit', 'hair', 'half', 'hall',
  'hand', 'handful', 'handle', 'happiness', 'harbor', 'hardware', 'harm', 'hat', 'headline', 'headquarters',
  'hearing', 'heart', 'heat', 'heaven', 'height', 'hell', 'help', 'hero', 'highlight', 'highway',
  'hill', 'hint', 'hip', 'historian', 'hit', 'hockey', 'hole', 'holiday', 'horse', 'hospital',
  'host', 'hotel', 'household', 'housing', 'humor', 'hundred', 'hunger', 'hunting', 'husband', 'ice',
  'icon', 'identification', 'identity', 'illness', 'illustration', 'image', 'imagination', 'impact', 'implement', 'implication',
  'importance', 'impression', 'improvement', 'incident', 'income', 'increase', 'independence', 'index', 'indication', 'individual',
  'industry', 'inflation', 'ingredient', 'initial', 'initiative', 'injury', 'inner', 'innovation', 'input', 'inquiry',
  'inside', 'insight', 'inspection', 'inspector', 'instance', 'institution', 'instruction', 'instrument', 'insurance', 'integration',
  'integrity', 'intelligence', 'intention', 'interaction', 'interest', 'interior', 'internet', 'interpretation', 'intervention', 'interview',
  'introduction', 'investigation', 'investment', 'investor', 'invitation', 'involvement', 'iron', 'island', 'item', 'jacket',
  'jail', 'jet', 'jewel', 'journey', 'joy', 'judge', 'judgment', 'juice', 'jump', 'junior',
  'jury', 'justice', 'key', 'kick', 'kingdom', 'kiss', 'kitchen', 'knee', 'knife', 'knowledge',
  'lab', 'label', 'labor', 'laboratory', 'ladder', 'lady', 'lake', 'land', 'landscape', 'lane',
  'language', 'lap', 'laptop', 'layer', 'leadership', 'leaf', 'league', 'leather', 'lecture', 'leg',
  'legacy', 'legend', 'legislation', 'length', 'lesson', 'letter', 'liability', 'liberal', 'library', 'license',
  'lifestyle', 'lifetime', 'lighting', 'limit', 'limitation', 'link', 'lip', 'liquid', 'list', 'listener',
  'literature', 'loan', 'location', 'logic', 'look', 'lord', 'loss', 'love', 'lover', 'luck',
  'lunch', 'lung', 'machine', 'magazine', 'magic', 'mail', 'maintenance', 'majority', 'maker', 'male',
  'mall', 'man', 'management', 'manager', 'manner', 'manufacturer', 'manufacturing', 'map', 'margin', 'mark',
  'market', 'marketing', 'marriage', 'mass', 'master', 'match', 'material', 'math', 'matter', 'maximum',
  'meal', 'meaning', 'measure', 'measurement', 'meat', 'mechanism', 'media', 'medicine', 'medium', 'meeting',
  'membership', 'memory', 'mental', 'mention', 'menu', 'mercy', 'message', 'metal', 'method', 'middle',
  'midnight', 'might', 'mile', 'milk', 'mill', 'million', 'mind', 'mine', 'minimum', 'minister',
  'minority', 'miracle', 'mirror', 'mission', 'mistake', 'mix', 'mixture', 'mode', 'model', 'mom',
  'monitor', 'mood', 'moon', 'morning', 'mortgage', 'motion', 'motivation', 'motor', 'mount', 'mountain',
  'mouse', 'mouth', 'movie', 'mud', 'murder', 'muscle', 'museum', 'music', 'mystery', 'myth',
  'nail', 'narrative', 'nation', 'native', 'nature', 'navy', 'neck', 'need', 'negotiation', 'neighbor',
  'neighborhood', 'nerve', 'net', 'network', 'news', 'newspaper', 'noise', 'nomination', 'noon', 'norm',
  'north', 'nose', 'notebook', 'novel', 'nurse', 'nursing', 'nut', 'object', 'objective', 'obligation',
  'observation', 'observer', 'obstacle', 'occasion', 'occupation', 'ocean', 'offense', 'officer', 'official', 'oil',
  'opening', 'opera', 'operation', 'operator', 'opinion', 'opponent', 'opportunity', 'opposite', 'opposition', 'option',
  'orange', 'orchestra', 'ordinary', 'organization', 'orientation', 'origin', 'original', 'other', 'outcome', 'output',
  'outside', 'oven', 'owner', 'ownership', 'pace', 'pack', 'package', 'page', 'pain', 'paint',
  'painter', 'painting', 'pair', 'palace', 'panel', 'panic', 'paper', 'paragraph', 'parent', 'park',
  'parking', 'participant', 'participation', 'partner', 'partnership', 'passage', 'passenger', 'passion', 'past', 'path',
  'patience', 'patient', 'pattern', 'pause', 'payment', 'peace', 'peak', 'penalty', 'pension', 'pepper',
  'percentage', 'perception', 'performance', 'period', 'permission', 'personality', 'perspective', 'phase', 'phenomenon', 'philosophy',
  'phone', 'photo', 'photograph', 'photographer', 'photography', 'phrase', 'physician', 'physics', 'piano', 'picture',
  'pie', 'piece', 'pilot', 'pine', 'pink', 'pipe', 'pitch', 'pizza', 'plane', 'planet',
  'planning', 'plant', 'plastic', 'plate', 'platform', 'pleasure', 'plenty', 'plot', 'pocket', 'poem',
  'poet', 'poetry', 'pole', 'police', 'policy', 'politician', 'politics', 'poll', 'pollution', 'pool',
  'pop', 'popular', 'population', 'pork', 'port', 'portion', 'portrait', 'pose', 'position', 'positive',
  'possession', 'possibility', 'post', 'pot', 'potato', 'potential', 'pound', 'poverty', 'powder', 'prayer',
  'precedent', 'preference', 'pregnancy', 'preparation', 'presence', 'presentation', 'preservation', 'presidency', 'press', 'pressure',
  'price', 'pride', 'priest', 'primary', 'prime', 'princess', 'principal', 'principle', 'print', 'printer',
  'printing', 'priority', 'prison', 'prisoner', 'privacy', 'prize', 'problem', 'procedure', 'proceeding', 'producer',
  'product', 'production', 'profession', 'professional', 'professor', 'profile', 'profit', 'progress', 'project', 'promise',
  'promotion', 'proof', 'property', 'proportion', 'proposal', 'prosecution', 'prospect', 'protection', 'protein', 'protest',
  'provider', 'province', 'provision', 'psychology', 'publication', 'publicity', 'publisher', 'punishment', 'pupil', 'purchase',
  'purple', 'purpose', 'pursuit', 'quality', 'quantity', 'quarter', 'queen', 'quest', 'quote', 'race',
  'radical', 'radio', 'rage', 'rail', 'rain', 'rainbow', 'range', 'rank', 'rape', 'rate',
  'ratio', 'reaction', 'reader', 'reading', 'reality', 'realm', 'rear', 'reasoning', 'rebel', 'receipt',
  'receiver', 'reception', 'recipe', 'recognition', 'recommendation', 'recording', 'recovery', 'recreation', 'reduction', 'reference',
  'reflection', 'reform', 'refrigerator', 'refugee', 'refusal', 'region', 'regulation', 'rejection', 'relation', 'relationship',
  'relative', 'relief', 'religion', 'remainder', 'remark', 'remedy', 'reminder', 'rent', 'repeat', 'replacement',
  'reply', 'reporter', 'representation', 'representative', 'republic', 'reputation', 'requirement', 'rescue', 'researcher', 'reservation',
  'reserve', 'resident', 'resignation', 'resistance', 'resolution', 'resort', 'resource', 'respect', 'response', 'responsibility',
  'restaurant', 'restriction', 'retirement', 'revenue', 'reverse', 'revolution', 'reward', 'rhetoric', 'rhythm', 'rice',
  'ride', 'rifle', 'ring', 'riot', 'rise', 'ritual', 'river', 'road', 'rock', 'role',
  'roof', 'root', 'rope', 'rose', 'rough', 'round', 'route', 'routine', 'row', 'royal',
  'ruin', 'running', 'rural', 'rush', 'safety', 'sailing', 'saint', 'salad', 'salary', 'sale',
  'salmon', 'salt', 'sample', 'sanction', 'sand', 'satellite', 'satisfaction', 'sauce', 'saving', 'scale',
  'scandal', 'scene', 'schedule', 'scheme', 'scholar', 'scholarship', 'school', 'science', 'scientist', 'scope',
  'score', 'screen', 'script', 'sea', 'seal', 'search', 'season', 'seat', 'second', 'secret',
  'secretary', 'section', 'sector', 'security', 'seed', 'segment', 'selection', 'self', 'senate', 'senator',
  'senior', 'sense', 'sensitivity', 'sentence', 'sequence', 'series', 'servant', 'session', 'setting', 'settlement',
  'sex', 'shade', 'shadow', 'shame', 'shelter', 'shift', 'shine', 'ship', 'shipping', 'shirt',
  'shock', 'shoe', 'shooting', 'shore', 'shortage', 'shoulder', 'shower', 'sibling', 'sight', 'signal',
  'signature', 'significance', 'silence', 'silver', 'similarity', 'sin', 'singer', 'sister', 'site', 'situation',
  'size', 'ski', 'skill', 'skin', 'sky', 'slave', 'slice', 'slide', 'slip', 'slope',
  'smell', 'snow', 'soccer', 'society', 'sock', 'software', 'soil', 'solar', 'soldier', 'solid',
  'solution', 'somebody', 'son', 'song', 'sort', 'soul', 'source', 'south', 'southern', 'space',
  'speaker', 'special', 'specialist', 'species', 'specific', 'spectrum', 'speech', 'speed', 'spell', 'spending',
  'sphere', 'spirit', 'spiritual', 'spokesman', 'sponsor', 'sport', 'spot', 'spread', 'spring', 'square',
  'stability', 'stadium', 'staff', 'stage', 'stair', 'stake', 'standard', 'standing', 'star', 'start',
  'startup', 'station', 'statistics', 'status', 'statute', 'steel', 'step', 'stimulus', 'stock', 'stomach',
  'stone', 'storage', 'storm', 'stranger', 'strategy', 'stream', 'street', 'strength', 'stress', 'stretch',
  'string', 'strip', 'stroke', 'structure', 'struggle', 'student', 'studio', 'stuff', 'style', 'subject',
  'substance', 'success', 'sugar', 'suggestion', 'suicide', 'summer', 'summit', 'sun', 'super', 'supermarket',
  'supply', 'supporter', 'surface', 'surgery', 'surplus', 'survey', 'survival', 'survivor', 'suspension', 'switch',
  'symbol', 'symptom', 'syndrome', 'tale', 'talent', 'tank', 'tape', 'task', 'tax', 'tea',
  'teaching', 'technique', 'technology', 'teen', 'teenager', 'telephone', 'television', 'temperature', 'temple', 'tendency',
  'tennis', 'tension', 'tent', 'term', 'terminal', 'territory', 'terror', 'terrorism', 'terrorist', 'testing',
  'text', 'texture', 'thanks', 'theater', 'theme', 'theology', 'theory', 'therapy', 'thinking', 'thought',
  'threat', 'threshold', 'throat', 'throne', 'ticket', 'tie', 'timber', 'timing', 'tip', 'tire',
  'tissue', 'title', 'tobacco', 'toe', 'tolerance', 'tomato', 'tomorrow', 'tone', 'tongue', 'tonight',
  'tool', 'tooth', 'topic', 'total', 'touch', 'tough', 'tour', 'tourism', 'tourist', 'tournament',
  'tower', 'town', 'trace', 'track', 'tradition', 'traffic', 'tragedy', 'trail', 'trailer', 'training',
  'trait', 'transaction', 'transformation', 'transition', 'transmission', 'transport', 'transportation', 'trash', 'travel', 'traveler',
  'treasure', 'treatment', 'treaty', 'tree', 'tremendous', 'trend', 'trial', 'tribe', 'trick', 'trip',
  'trouble', 'troop', 'truck', 'truth', 'tube', 'tune', 'tunnel', 'turkey', 'twin', 'type',
  'uncle', 'understanding', 'unemployment', 'union', 'unique', 'unit', 'unity', 'universe', 'university', 'unknown',
  'upper', 'urban', 'user', 'utility', 'vacation', 'valley', 'valuable', 'value', 'variable', 'variation',
  'variety', 'vegetable', 'vehicle', 'venture', 'venue', 'version', 'veteran', 'vice', 'victim', 'victory',
  'video', 'village', 'violation', 'violence', 'virtue', 'virus', 'vision', 'visitor', 'visual', 'voice',
  'volume', 'volunteer', 'vulnerability', 'wage', 'walk', 'walking', 'wall', 'wallet', 'warning', 'warrior',
  'wave', 'way', 'weakness', 'wealth', 'weapon', 'weather', 'web', 'website', 'wedding', 'weekend',
  'weight', 'welfare', 'west', 'western', 'wheel', 'while', 'whisper', 'wife', 'wild', 'wildlife',
  'window', 'wine', 'wing', 'winner', 'winter', 'wire', 'wisdom', 'witness', 'wolf', 'wonder',
  'wood', 'woods', 'wool', 'workshop', 'worship', 'worth', 'wound', 'writer', 'writing', 'yard',
  'yellow', 'yesterday', 'youth', 'zone',
  
  // Extended adjectives
  'absolute', 'abstract', 'academic', 'acceptable', 'accessible', 'accurate', 'active', 'actual', 'acute', 'additional',
  'adequate', 'adjacent', 'administrative', 'advanced', 'adverse', 'aesthetic', 'affordable', 'aggressive', 'agricultural', 'alive',
  'alleged', 'alternative', 'amazing', 'ambitious', 'ancient', 'angry', 'annual', 'anonymous', 'anxious', 'apparent',
  'applicable', 'appropriate', 'arbitrary', 'armed', 'artificial', 'artistic', 'ashamed', 'asleep', 'athletic', 'attractive',
  'automatic', 'aware', 'awful', 'awkward', 'bare', 'basic', 'beautiful', 'beloved', 'beneficial', 'bent',
  'bitter', 'blank', 'blind', 'bloody', 'blue', 'bold', 'boring', 'bound', 'brave', 'brief',
  'bright', 'brilliant', 'broad', 'broken', 'brown', 'busy', 'calm', 'capable', 'capital', 'careful',
  'casual', 'central', 'challenging', 'characteristic', 'cheap', 'chemical', 'chief', 'chronic', 'circular', 'civil',
  'classic', 'classical', 'clean', 'clever', 'clinical', 'close', 'closed', 'coastal', 'cognitive', 'cold',
  'collective', 'colonial', 'colorful', 'comfortable', 'comic', 'commercial', 'committed', 'communist', 'compact', 'comparable',
  'comparative', 'compatible', 'competitive', 'complete', 'complex', 'complicated', 'comprehensive', 'concerned', 'concrete', 'conditional',
  'confident', 'conscious', 'conservative', 'considerable', 'consistent', 'constant', 'constitutional', 'contemporary', 'content', 'continuous',
  'controversial', 'convenient', 'conventional', 'convinced', 'cool', 'cooperative', 'corporate', 'costly', 'crazy', 'creative',
  'criminal', 'critical', 'cruel', 'cultural', 'curious', 'custom', 'cute', 'daily', 'dangerous', 'decent',
  'decisive', 'deep', 'defensive', 'deliberate', 'delicate', 'delicious', 'democratic', 'dependent', 'depressed', 'desperate',
  'detailed', 'determined', 'developing', 'different', 'difficult', 'digital', 'diplomatic', 'direct', 'dirty', 'disabled',
  'disappointed', 'distinct', 'distinctive', 'diverse', 'divine', 'domestic', 'dominant', 'double', 'downtown', 'dramatic',
  'drawn', 'dreadful', 'driving', 'dry', 'dual', 'due', 'dull', 'dynamic', 'eager', 'eastern',
  'ecological', 'educational', 'effective', 'efficient', 'elaborate', 'elderly', 'electoral', 'electric', 'electrical', 'electronic',
  'elegant', 'elementary', 'eligible', 'embarrassed', 'emotional', 'empirical', 'empty', 'encouraging', 'endless', 'engaged',
  'enormous', 'entire', 'enthusiastic', 'environmental', 'equivalent', 'essential', 'eternal', 'ethical', 'ethnic', 'european',
  'everyday', 'evident', 'evil', 'evolutionary', 'exact', 'excellent', 'exceptional', 'excessive', 'excited', 'exciting',
  'exclusive', 'existing', 'exotic', 'expensive', 'experienced', 'experimental', 'explicit', 'extensive', 'external', 'extra',
  'extraordinary', 'extreme', 'facial', 'fair', 'faithful', 'false', 'familiar', 'famous', 'fancy', 'fantastic',
  'fascinating', 'fashionable', 'fast', 'fat', 'fatal', 'favorable', 'federal', 'fellow', 'female', 'feminine',
  'fierce', 'filthy', 'fine', 'firm', 'fixed', 'flat', 'flexible', 'following', 'fond', 'foolish',
  'foreign', 'formal', 'fortunate', 'forward', 'founding', 'fragile', 'frank', 'free', 'frequent', 'fresh',
  'friendly', 'front', 'frozen', 'fruitful', 'frustrated', 'full', 'functional', 'fundamental', 'funny', 'furious',
  'future', 'generous', 'genetic', 'gentle', 'genuine', 'giant', 'given', 'glad', 'global', 'golden',
  'gorgeous', 'gradual', 'grand', 'grateful', 'gray', 'green', 'grey', 'grim', 'gross', 'growing',
  'guilty', 'handsome', 'handy', 'happy', 'harsh', 'healthy', 'heavy', 'helpful', 'hidden', 'historic',
  'historical', 'holy', 'homeless', 'honest', 'horizontal', 'horrible', 'hostile', 'household', 'huge', 'humble',
  'hungry', 'ideal', 'identical', 'ill', 'illegal', 'immediate', 'immense', 'immune', 'imperial', 'implicit',
  'impossible', 'impressed', 'impressive', 'improved', 'inadequate', 'inappropriate', 'incredible', 'independent', 'indigenous', 'indirect',
  'individual', 'industrial', 'inevitable', 'inferior', 'infinite', 'influential', 'informal', 'inherent', 'innocent', 'innovative',
  'instant', 'institutional', 'instrumental', 'insufficient', 'intellectual', 'intelligent', 'intense', 'intensive', 'interested', 'interesting',
  'interim', 'intermediate', 'internal', 'intimate', 'involved', 'irrelevant', 'isolated', 'joint', 'junior', 'keen',
  'key', 'kind', 'known', 'laid', 'large', 'lasting', 'late', 'lateral', 'latin', 'latter',
  'leading', 'left', 'legislative', 'legitimate', 'lengthy', 'lesser', 'liberal', 'limited', 'linear', 'linguistic',
  'literary', 'live', 'living', 'logical', 'lonely', 'loose', 'lost', 'loud', 'lovely', 'low',
  'lower', 'lucky', 'mad', 'magnetic', 'magnificent', 'mainland', 'mainstream', 'male', 'mandatory', 'manual',
  'marginal', 'marine', 'marked', 'married', 'massive', 'mathematical', 'mature', 'maximum', 'meaningful', 'mechanical',
  'medieval', 'medium', 'mental', 'mere', 'middle', 'mild', 'military', 'mineral', 'minimal', 'minimum',
  'minor', 'miserable', 'missing', 'mixed', 'mobile', 'moderate', 'modest', 'molecular', 'monetary', 'monthly',
  'moral', 'multiple', 'municipal', 'musical', 'mutual', 'mysterious', 'naked', 'narrow', 'nasty', 'native',
  'naval', 'nearby', 'neat', 'negative', 'neighboring', 'nervous', 'net', 'neutral', 'new', 'noble',
  'noisy', 'nominal', 'normal', 'northern', 'notable', 'nuclear', 'numerous', 'objective', 'obvious', 'occasional',
  'occupational', 'odd', 'official', 'okay', 'ongoing', 'operational', 'opposite', 'optimal', 'optimistic', 'oral',
  'orange', 'organic', 'organizational', 'oriental', 'outer', 'outstanding', 'overall', 'overseas', 'overwhelming', 'own',
  'painful', 'pale', 'parallel', 'partial', 'particular', 'passive', 'patient', 'peculiar', 'perfect', 'permanent',
  'persistent', 'philosophical', 'pink', 'plain', 'plastic', 'pleasant', 'pleased', 'plus', 'pointed', 'polar',
  'political', 'popular', 'portable', 'positive', 'postal', 'potential', 'powerful', 'practical', 'precious', 'precise',
  'predictable', 'pregnant', 'preliminary', 'premier', 'premium', 'prepared', 'presidential', 'pretty', 'prevalent', 'previous',
  'primary', 'prime', 'primitive', 'principal', 'printed', 'prior', 'private', 'probable', 'productive', 'professional',
  'profound', 'progressive', 'prominent', 'promising', 'pronounced', 'proper', 'proportional', 'proposed', 'prospective', 'protective',
  'proud', 'provincial', 'psychological', 'purple', 'qualified', 'quick', 'quiet', 'racial', 'radical', 'random',
  'rapid', 'rare', 'rational', 'raw', 'ready', 'realistic', 'rear', 'reasonable', 'red', 'reduced',
  'regional', 'regular', 'regulatory', 'related', 'relative', 'relevant', 'reliable', 'religious', 'reluctant', 'remaining',
  'remarkable', 'remote', 'renowned', 'repeated', 'representative', 'republican', 'required', 'residential', 'resistant', 'resolved',
  'respective', 'responsible', 'responsive', 'restricted', 'resulting', 'retail', 'retired', 'revolutionary', 'rich', 'ridiculous',
  'rigid', 'risky', 'rival', 'robust', 'romantic', 'rough', 'round', 'royal', 'rude', 'rural',
  'russian', 'sacred', 'sad', 'safe', 'salty', 'satisfied', 'scared', 'scattered', 'scientific', 'secondary',
  'secure', 'selective', 'semantic', 'senior', 'sensible', 'sensitive', 'separate', 'sequential', 'serious', 'severe',
  'sexual', 'shallow', 'shared', 'sharp', 'sheer', 'short', 'shy', 'sick', 'significant', 'silent',
  'silly', 'silver', 'simultaneous', 'sincere', 'skilled', 'slight', 'slim', 'slow', 'smart', 'smooth',
  'sober', 'soft', 'solar', 'sole', 'solid', 'sophisticated', 'sore', 'sorry', 'sound', 'sour',
  'south', 'southern', 'spare', 'spatial', 'spectacular', 'spiritual', 'splendid', 'spontaneous', 'stable', 'standard',
  'standing', 'stark', 'statistical', 'steady', 'steep', 'sticky', 'stiff', 'still', 'stock', 'straight',
  'straightforward', 'strange', 'strategic', 'strict', 'striking', 'structural', 'stuck', 'stupid', 'subsequent', 'substantial',
  'subtle', 'successful', 'successive', 'sudden', 'sufficient', 'suitable', 'super', 'superior', 'supposed', 'supreme',
  'surgical', 'surplus', 'surprised', 'surprising', 'surrounding', 'suspicious', 'sustainable', 'sweet', 'swift', 'symbolic',
  'sympathetic', 'systematic', 'tactical', 'tall', 'technical', 'technological', 'teenage', 'temporary', 'tender', 'tense',
  'terminal', 'terrible', 'territorial', 'thick', 'thin', 'thorough', 'thoughtful', 'tight', 'tiny', 'tired',
  'top', 'total', 'tough', 'toxic', 'traditional', 'tragic', 'tremendous', 'tribal', 'tricky', 'tropical',
  'troubled', 'typical', 'ugly', 'ultimate', 'unable', 'uncertain', 'uncomfortable', 'underlying', 'unexpected', 'unfair',
  'unfortunate', 'unhappy', 'uniform', 'universal', 'unknown', 'unlikely', 'unnecessary', 'unprecedented', 'unusual', 'upper',
  'upset', 'urban', 'urgent', 'used', 'useful', 'usual', 'valid', 'valuable', 'variable', 'vast',
  'verbal', 'vertical', 'viable', 'violent', 'virtual', 'visible', 'visual', 'vital', 'vivid', 'voluntary',
  'vulnerable', 'warm', 'weak', 'wealthy', 'weekly', 'weird', 'welcome', 'well', 'western', 'wet',
  'white', 'whole', 'wicked', 'wide', 'widespread', 'wild', 'willing', 'wise', 'wonderful', 'wooden',
  'working', 'worldwide', 'worried', 'worse', 'worst', 'worthy', 'wrong', 'yellow', 'young',
]);

/**
 * Extended list of 20K common words for rare word detection
 * Words not in this list are considered "rare" and get extra display time
 */
export const COMMON_WORDS_20K = new Set([
  ...COMMON_WORDS_5K,
  
  // Technical and specialized vocabulary commonly found in reading materials
  'algorithm', 'analysis', 'application', 'architecture', 'assessment', 'assumption',
  'bibliography', 'biodiversity', 'biotechnology', 'calculation', 'cardiovascular',
  'characteristic', 'chronological', 'circumference', 'classification', 'collaboration',
  'communication', 'comprehensive', 'concentration', 'configuration', 'consciousness',
  'constitutional', 'contemporary', 'contradiction', 'contribution', 'controversial',
  'coordination', 'correspondence', 'cryptocurrency', 'cybersecurity', 'demographic',
  'demonstration', 'determination', 'differentiation', 'discrimination', 'documentation',
  'electromagnetic', 'environmental', 'epidemiological', 'establishment', 'experimentation',
  'extraordinary', 'functionality', 'generalization', 'globalization', 'heterogeneous',
  'homogeneous', 'identification', 'implementation', 'implication', 'infrastructure',
  'initialization', 'instantiation', 'institutionalization', 'instrumentation', 'integration',
  'interdisciplinary', 'internationalization', 'interpretation', 'interrelationship',
  'investigation', 'justification', 'manifestation', 'manipulation', 'marginalization',
  'materialization', 'maximization', 'methodology', 'microorganism', 'minimization',
  'misinterpretation', 'modernization', 'multiplication', 'nanotechnology', 'naturalization',
  'neurological', 'neutralization', 'normalization', 'objectification', 'operationalization',
  'optimization', 'organizational', 'oversimplification', 'parameterization', 'pathological',
  'personalization', 'pharmaceutical', 'phenomenological', 'philosophical', 'photosynthesis',
  'physiological', 'polarization', 'popularization', 'precipitation', 'predetermination',
  'predominantly', 'preoccupation', 'preponderance', 'presupposition', 'prioritization',
  'privatization', 'problematization', 'professionalism', 'professionalization', 'proliferation',
  'proportionality', 'psychoanalysis', 'psychological', 'quantification', 'questionnaire',
  'rationalization', 'recapitulation', 'reconfiguration', 'reconciliation', 'reconstruction',
  'redistribution', 'reevaluation', 'regionalization', 'rehabilitation', 'reinterpretation',
  'reorganization', 'representation', 'reproducibility', 'responsibility', 'restructuring',
  'revitalization', 'secularization', 'semiconductor', 'simplification', 'socialization',
  'socioeconomic', 'sophistication', 'specialization', 'specification', 'standardization',
  'stratification', 'subjectification', 'subordination', 'substantiation', 'sustainability',
  'synchronization', 'systematization', 'telecommunication', 'thermodynamic', 'transformation',
  'transnational', 'transportation', 'triangulation', 'underestimation', 'underrepresentation',
  'understanding', 'unemployment', 'universalization', 'unprecedented', 'visualization',
  'vulnerability', 'westernization',
  
  // Academic and scientific terms
  'anthropology', 'archaeology', 'astrophysics', 'biochemistry', 'bioinformatics',
  'biomechanics', 'biophysics', 'cartography', 'climatology', 'cosmology',
  'criminology', 'crystallography', 'demography', 'dermatology', 'ecology',
  'economics', 'embryology', 'endocrinology', 'entomology', 'epidemiology',
  'epistemology', 'ethnography', 'etymology', 'gastroenterology', 'genetics',
  'geochemistry', 'geography', 'geology', 'geomorphology', 'geophysics',
  'hematology', 'histology', 'hydrology', 'immunology', 'jurisprudence',
  'lexicography', 'linguistics', 'malacology', 'meteorology', 'microbiology',
  'mineralogy', 'morphology', 'musicology', 'nephrology', 'neurology',
  'neuroscience', 'oceanography', 'oncology', 'ontology', 'ophthalmology',
  'ornithology', 'orthopedics', 'paleontology', 'parasitology', 'pathology',
  'pedagogy', 'petrology', 'pharmacology', 'phenomenology', 'philology',
  'phonology', 'physiology', 'primatology', 'psychiatry', 'radiology',
  'seismology', 'semantics', 'semiotics', 'sociology', 'spectroscopy',
  'stratigraphy', 'taxonomy', 'technology', 'teleology', 'terminology',
  'thermodynamics', 'topology', 'toxicology', 'urology', 'virology',
  'volcanology', 'zoology',
]);
